## 학습목표
1. boolean indexing의 이해

#### Boolean indexing
  - ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

* 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
 - 예) 짝수인 경우만 찾아보기

In [1]:
import numpy as np

In [6]:
np.random.seed(100)
x = np.random.randint(1, 100, size = 10)
x

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99])

- bool 리스트를 인덱스로 전달

In [12]:
even_mask = x % 2 == 0
even_mask

array([False, False,  True,  True,  True, False, False, False, False,
       False])

In [13]:
# True값만 추출
x[even_mask]

array([68, 88, 80])

In [14]:
# 한번에 하는 법
x[x % 2 == 0]

array([68, 88, 80])

####  다중조건 사용하기
 - 파이썬 논리 연산지인 and, or, not 키워드 사용 불가
 - & - AND 
 - | - OR 

In [16]:
x % 2 == 0
x >70

x[(x % 2 ==0) & (x > 70)]

array([88, 80])

In [17]:
x % 2 != 0
x > 40

x[(x % 2 != 0) | (x > 40)]

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99])

#### 예제) 2019년 7월 서울 평균기온 데이터
 - 평균기온이 25도를 넘는 날수는?
 - 평균기온이 25를 넘는 날의 평균 기온은?

In [18]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [19]:
len(temp)

31

In [21]:
temp > 25.0

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False, False, False,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [20]:
temp[temp > 25.0]

array([25.4, 27.6, 29.7, 26.7, 25.1, 25.9, 25.6, 26.9, 28.6, 28. , 25.1,
       26.7, 28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [22]:
len(temp[temp > 25.0])
# == np.sum(temp > 25.0) True값은 1이기 때문에 같음

21

In [23]:
np.mean(temp[temp > 25.0])

26.857142857142858