# UNIT 22 행열 전환과 형태 변형하기

In [1]:
import numpy as np

Tensor3D = np.array(['MMM', 'ABI', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'])
Tensor3D

array(['MMM', 'ABI', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [3]:
Tensor2D = Tensor3D.reshape(2,4)
Tensor2D

array([['MMM', 'ABI', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [13]:
Tensor4D = Tensor3D.reshape(4,1,2)
Tensor4D

array([[['MMM', 'ABI']],

       [['ABBV', 'ACN']],

       [['ACE', 'ATVI']],

       [['ADBE', 'ADT']]], dtype='<U4')

In [15]:
import numpy as np

Tensor3D = np.arange(2*3*4).reshape(2,3,4)
print(Tensor3D.shape)
Tensor3D


(2, 3, 4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
a = np.sum(Tensor3D, axis = 0)
a

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [17]:
b = np.sum(Tensor3D, axis = 1)
b

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [18]:
c = np.sum(Tensor3D, axis = 2)
c

array([[ 6, 22, 38],
       [54, 70, 86]])