# UNIT 25 유니버셜 함수 파헤치기

### 벡터화된 유니버셜 함수(ufunc)

#### 유니버셜 함수는 브로드캐스팅의 함수형 버전

#### 유니버셜 함수를 사용 -> 한번에 배열의 모든 아이템에 적용

#### Numpy에서는 다양한 유니버셜 함수를 제공

- 사칙연산 : add(), multiply(), negative(), exp(), log(), sqrt()

- 삼각함수 : sin(), cos(), hypot()

- 비트 단위 : bitwise_and(), left_shift()

- 관계형, 논리 : less(), logical_not(), equal()

- maximum()과 minimum()

- 부동소수점에 적용할 수 있는 함수 : isinf(), infinite(), floor(), isnan()

### 2016년 1월 10일을 기준으로 전후 주식 8개의 가격

In [2]:
import numpy as np

stocks = np.array([140.49, 0.97, 40.68, 41.53, 55.7,
                   57.21, 98.2, 99.19, 109.96, 111.47,
                   35.71, 36.72, 87.85, 89.11, 30.22,
                   30.91])

stocks

array([140.49,   0.97,  40.68,  41.53,  55.7 ,  57.21,  98.2 ,  99.19,
       109.96, 111.47,  35.71,  36.72,  87.85,  89.11,  30.22,  30.91])

In [3]:
# 기준 시점 전 그룹 / 후 그룹으로 나열해서 2*8행렬로 만든다

stocks = stocks.reshape(8,2).T
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.97,  41.53,  57.21,  99.19, 111.47,  36.72,  89.11,  30.91]])

#### np.greater(x1, x2) : element-wise로 x1 > x2 비교 연산 결과 T or F 반환

In [4]:
# stocks[0] > stocks[1] 비교 후, 크면 True, 작으면 False

fall = np.greater(stocks[0], stocks[1])
fall

array([ True, False, False, False, False, False, False, False])

In [5]:
sap = np.array(["MMM", "ABT", "ABBV", "ACN", 
                "ACE", "ATVI", "ADBE", "ADT"])
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [6]:
# 불 인덱싱을 사용해서 원하는 결과 출력

sap[fall]   # True값 만 출력

array(['MMM'], dtype='<U4')

### 예제 1

In [11]:
import numpy as np

a = np.array([4,2])
print(a)

b = np.array([2,3])
print(b)

np.greater(a,b) # 4 > 2 True, 2 > 3 False

[4 2]
[2 3]


array([ True, False])

In [12]:
# 위와 같은 코드

a = np.array([4,2])
b = np.array([2,3])
a>b

array([ True, False])

### 예제 2

In [13]:
a = list([4,2])
print(a)

b = list([2,3])
print(b)

np.greater(a,b)

[4, 2]
[2, 3]


array([ True, False])

In [15]:
# 위와 같은 코드

a = list([4,2])
b = list([2,3])
a>b  # 위와 결과값이 다르게 출력됨

True

### isnan()을 이용해 결측치 찾기

매개변수가 숫자인지 아닌지 검사하는 함수(nan은 not a number)

np.isnan(value)

- value는 검사할 값을 입력
- value가 전통적인 숫자, IEEE 754 부동소수점 기준, 양수 무한대(inf), 음의 무한대, 불(Bool)값이면 False, 그렇지 않고 nan(float("nan"))이면 True를 반환

In [17]:
a = np.array([123.1, True, False, np.nan, np.inf, np.NINF])
print(a)
np.isnan(a)

# np.nan => True / 나머지 => False

[123.1   1.    0.    nan   inf  -inf]


array([False, False, False,  True, False, False])

### 예제

In [20]:
# 새 MMM 주식 가격이 결측치라고 가정해 보자.

stocks[1,0] = np.nan
print(stocks)
np.isnan(stocks)

[[140.49  40.68  55.7   98.2  109.96  35.71  87.85  30.22]
 [   nan  41.53  57.21  99.19 111.47  36.72  89.11  30.91]]


array([[False, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False]])

In [21]:
# 결측치를 수정해보자. 이보다 더 나쁠 수는 없다.

stocks[np.isnan(stocks)] = 0
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.  ,  41.53,  57.21,  99.19, 111.47,  36.72,  89.11,  30.91]])