# UNIT 24 브로드 캐스팅

### 브로드 캐스팅

In [22]:
a = np.arange(4)
b = np.arange(1,5)
print(a)
print(b)
print(a+b)
a*5

[0 1 2 3]
[1 2 3 4]
[1 3 5 7]


array([ 0,  5, 10, 15])

In [11]:
import numpy as np

noise = np.eye(4)+0.01*np.ones((4,))
noise

array([[1.01, 0.01, 0.01, 0.01],
       [0.01, 1.01, 0.01, 0.01],
       [0.01, 0.01, 1.01, 0.01],
       [0.01, 0.01, 0.01, 1.01]])

In [14]:
noise = np.eye(4) + 0.01 * np.random.random([4,4])
noise

array([[1.00180224, 0.00826095, 0.00480111, 0.00883966],
       [0.00142395, 1.00270018, 0.00971175, 0.00914919],
       [0.00164875, 0.00704989, 1.00087886, 0.00310632],
       [0.00975338, 0.00920167, 0.00327756, 1.00346063]])

#### np.round() 사용하여 모든 행렬의 요소들을 소수점 두자리수만 표시되도록 반올림 처리

In [15]:
np.round(noise, 2)

array([[1.  , 0.01, 0.  , 0.01],
       [0.  , 1.  , 0.01, 0.01],
       [0.  , 0.01, 1.  , 0.  ],
       [0.01, 0.01, 0.  , 1.  ]])