# UNIT 21 배열 만들기

#### numpy모듈을 사용하기 위해선 conda prompt에서 
#### activate pyLab36 -> pip install numpy 설치해주기

### numpy 배열

In [1]:
# array()함수 - 임의의 리스트나 튜플 데이터를 배열로 만드는 함수

import numpy as np
numbers = np.array(range(1,11), copy=True)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# ones()함수 - 모든 배열원소를 1로 초기화
ones = np.ones([2,4], dtype =np.float64)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
# zeros()함수 - 모든 배열 원소를 0으로 초기화
zeros = np.zeros([2,4], dtype = np.float64)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
# empty()함수 - 정수 0이 아닌 빈 배열 만드는 함수
empty = np.empty([2,4], dtype =np.float64)
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# eye()함수 - 단위 행렬 만드는 함수
import numpy as np
eye = np.eye(5)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
# shape - 아직 변형되지 않았다면 원래 모양을 반환
ones.shape   # (2,4) => 2행 4열

(2, 4)

In [9]:
# ndim - len(numbers, shape)와 같다 / 배열 차원의 개수를 반환
numbers.ndim

1

In [10]:
# dtype - 데이터 타입 반환
zeros.dtype

dtype('float64')

In [13]:
# arange(start, stop, step, dtype = None) - 일정한 간격으로 배열된 배열 생성
np_numbers = np.arange(2,5,0.25) # 2~5까지 0.25 간격으로(끝 자리 5는 포함x)
np_numbers

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

In [14]:
# astype(dtype, casting ="unsafe", copy =True) 타입변경 함수
# 타입 유형 변경시 데이터 유실 가능성 있음
import numpy as np

np_numbers = np.arange(2,5,0.25)
np_numbers

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

In [17]:
np_numbers = np_numbers.astype(np.int)
np_numbers

array([2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

### 원천데이터 보존

#### 같은 데이터를 가지지만 다른 객체임

In [12]:
# 원천 데이터를 보존하려면 copy()함수 사용
# np_inumbers_copy = np_inumbers.copy()
# id : 메모리에 할당된 객체의 주소값 반환

import numpy as np

numbers = np.array(range(1,11))
print(numbers)

numbers_copy = numbers.copy()
numbers_copy[2]=100
print(numbers)

print(id(numbers), id(numbers_copy))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
2704290860368 2704290885760


#### 다른 데이터를 가지지만 같은 객체

In [11]:
import numpy as np

numbers = np.array(range(1,11))
print(numbers)

numbers_copy = numbers
numbers_copy[2]=100
print(numbers)
print(id(numbers), id(numbers_copy))

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2 100   4   5   6   7   8   9  10]
2704290860848 2704290860848
