# UNIT 23 인덱싱과 자르기 

### numpy배열은 인덱싱[i]과 슬라이싱[i:j]과 불 인덱싱이 가능함

In [3]:
# 데이터 셋 dirty에 있는 데이터에서 음수 값을 모두 0으로 만드는데 데이터 클리닝작업 수행
import numpy as np

dirty = np.array([9, 4, 1, -0.1, -0.2, -0.001])
whos_dirty = dirty < 0 # 불 배열을 불 인덱스로 사용한다.
whos_dirty

array([False, False, False,  True,  True,  True])

In [4]:
dirty[whos_dirty] = 0 # 모든 음수 값을 0으로 바꾼다.
dirty

array([9., 4., 1., 0., 0., 0.])

### 스마트 인덱싱

In [9]:
import numpy as np

sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [11]:
sap[[1, 2, -1]] # 해당되는 인덱스 출력

array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

### 스마트 슬라이싱

In [13]:
sap2d = sap.reshape(2,4)
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [24]:
# 변형된 배열에서 중간 열에 있는 모든 행 출력 (세로 n번째 출력)
# sap2d[:, [n]]

r1 = sap2d[:, [1]]  # 2차원 행렬 추출
print(r1, r1.shape)

[['ABT']
 ['ATVI']] (2, 1)


In [25]:
r2 = sap2d[:,1] # 1차원 배열
print(r2, r2.shape)

['ABT' 'ATVI'] (2,)


### numpy배열은 논리 연산자인 |(or)과 &(and), -(not)을 사용해서 여러 불 표현을 결합할 수 있음

In [8]:
# 관계형 연산자는 (<, <=, ==, >, >=)은 numpy배열에 불 연산을 수행하는
# &, |, -인 비트 연산자보다 처리 순위가 떨어짐

linear = np.arange(-1, 1.1, 0.2)
print(linear)
(linear <= 0.5) & (linear >= -0.5)

[-1.00000000e+00 -8.00000000e-01 -6.00000000e-01 -4.00000000e-01
 -2.00000000e-01 -2.22044605e-16  2.00000000e-01  4.00000000e-01
  6.00000000e-01  8.00000000e-01  1.00000000e+00]


array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False])