# UNIT 26 조건부 함수 이해하기

In [6]:
import numpy as np

stocks = np.array([140.49, 0.97, 40.68, 41.53, 55.7,
                   57.21, 98.2, 99.19, 109.96, 111.47,
                   35.71, 36.72, 87.85, 89.11, 30.22,
                   30.91])

stocks = stocks.reshape(8,2).T
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.97,  41.53,  57.21,  99.19, 111.47,  36.72,  89.11,  30.91]])

### 여러 조건부 함수

 - where(c, a, b)함수 : numpy의 삼항 연산자(if~else)
     - 불 배열(c)와 두 배열(a,b)을 파라미터로 받아서 d[i] = a[i] if c[i] else b[i]를 반환

In [8]:
# 삼항 연산자 where(c, a, b)
# c - 조건식 / a - 조건식이 참일 경우 / b - 조건식이 거짓일 경우

import numpy as np



changes = np.where(np.abs(stocks[1]-stocks[0])>1.00,
                  stocks[1]-stocks[0],0)
changes

array([-139.52,    0.  ,    1.51,    0.  ,    1.51,    1.01,    1.26,
          0.  ])

### nonzero( )

In [11]:
# nonzero() 0이 아닌 모든 엘리먼트의 인덱스를 반환

sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
sap[np.nonzero(changes)]

array(['MMM', 'ABBV', 'ACE', 'ATVI', 'ADBE'], dtype='<U4')

### np.any( ) 

 - 배열의 일부 요소가 0이 아닌 값을 가지면 True를 반환, 0이면 False를 반환
 - NaN, Inf, -Inf도 0값을 가지지 않기 때문에 True 반환
 - 불 자료형의 True는 True, False는 False로 반환

In [26]:
# or 같은 개념으로 이해하면 쉬움

np.any([[True, False], [True, True]])

True

In [25]:
# axis = 0(행) / axis = 1(열)

np.any([[True, False], [False, False]], axis = 0)

array([ True, False])

In [17]:
np.any([-1, 0, 5])

True

In [18]:
np.any(np.nan)

True

### np.all( )

 - 배열의 모든 요소가 0이 아닌 값을 가지면 True를 반환, 0이면 False를 반환
 - Nan, Inf, -Inf도 0값을 가지지 않기 때문에 True 반환
 - 불 자료형의 True는 True, False는 False로 반환

In [27]:
# and 같은 개념으로 이해하기

np.all([[True, False], [True, True]])

False

In [24]:
np.all([[True, False], [True, True]], axis=0)

array([ True, False])

In [21]:
np.all([-1, 4, 5])

True

In [22]:
np.all([1.0, np.nan])

True